### ISSUE TITLE
Create directory for config if it doesn't exist

### ISSUE THREAD

**Issue by snowe2010** [piotrmurach/tty-config#12]
### Describe the problem

I think it would be great if `#write` created the directory if it didn't exist. This would be useful for creating a config using the XDG Base Specification, because when creating a new app, the folder doesn't exist yet.

**Comment by piotrmurach** [comment]
Hi Tyler,

That sounds good to me. Could you please submit PR with a test case?

I'm curious how you use `tty-config` with XDG Spec? Would you mind sharing a code snippet.

**Comment by snowe2010** [comment]
Sure thing:

```ruby
    def setup_config(env)
      @config = TTY::Config.new
      @config.filename = 'cache'
      @config.extname = '.yaml'
      cache_dir = XDG::Cache.new.home + "sun"
      @config.prepend_path(cache_dir)
      cache_dir.mkpath unless cache_dir.exist?  # create the dir since it doesn't exist
      @config.read if @config.exist?

      @cache = @config.fetch(:pai, :overrides, env)
    end
```

Note in this case I'm using it with the cache dir, just because `tty-config` writes nice formatted output, but I also use it with the `XDG::Config` directory.

* [XDG library here](https://www.alchemists.io/projects/xdg/)

**Comment by piotrmurach** [comment]
@snowe2010 Took a bit longer than anticipated but now the `write` will create any missing directories. The assumption is that it will create `cache_dir` when it doesn't exist and is the first one in the list of all locations that `TTY::Config` knows about.

**Comment by snowe2010** [comment]
thanks! Now if only I can remember what project I was working on that used tty-config... 😅
