### ISSUE TITLE
Feature Request: Allow specification of file format independent of its file extension

### ISSUE THREAD

**Issue by fwolfst** [piotrmurach/tty-config#3]
It is debatable whether it is a good idea to _use_ "arbitrary" file extensions (like `.mytool.config`, `server.definition`, ...) but I think its a good idea to support the usage of it.

A probably simple way to do so would be to implement new arguments at `#unmarshal` and `#read`. This should be downward-compatible by providing sane defaults, like in this very rough sketch:

`def unmarshal(file, format: :auto) # :auto -> from extension`
and
`def read(file = find_file, format: :auto)` .

This would allow to read e.g. yaml-configuration files that do not end on .yml:
`config.read('mytool.config', format: :yaml)` .

**Comment by piotrmurach** [comment]
Very good point!

**Comment by piotrmurach** [comment]
Implemented as per discussion.
