### ISSUE TITLE
Feature Request: Add ability to read .ini type files

### ISSUE THREAD

**Issue by piotrmurach** [piotrmurach/tty-config#4]
Reading around it seems like .conf, .cfg and .ini files have similar specification whereby key-value pairs are separated by `=` character. There is [inifile](https://github.com/TwP/inifile) gem that parses .ini files types.

**Comment by fwolfst** [comment]
There is also the [parseconfig](https://github.com/datafolklabs/ruby-parseconfig/) gem.

**Comment by piotrmurach** [comment]
Thanks for finding parseconfig. Quickly looking through the source I can tell that it parses configuration file into its own source. That would be a pain! The toml and json gems are only parsers. In comparison the inifile gem has `IniFile::Parser` that can parse contents of ini file and stores it into a Ruby hash. This is more desirable.

**Comment by piotrmurach** [comment]
Implemented as per discussion.
